//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appoteka_v2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class dobavljaci
    {
        public dobavljaci()
        {
            this.narudzbe = new HashSet<narudzbe>();
        }
    
        public int IdDobavljac { get; set; }
        public string naziv { get; set; }
        public string OIB { get; set; }
        public string IBAN { get; set; }
        public string adresa { get; set; }
    
        public virtual ICollection<narudzbe> narudzbe { get; set; }
    }
}
