//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appoteka_v2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class hzzoKlijent
    {
        public hzzoKlijent()
        {
            this.hzzoRecept = new HashSet<hzzoRecept>();
        }
    
        public string OIB { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string zdrastvenaIskaznica { get; set; }
    
        public virtual ICollection<hzzoRecept> hzzoRecept { get; set; }
    }
}
