//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appoteka_v2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class hzzoRecept
    {
        public int idRecepta { get; set; }
        public Nullable<System.DateTime> datumIzdavanja { get; set; }
        public Nullable<System.DateTime> datumPocetka { get; set; }
        public Nullable<System.DateTime> datumIsteka { get; set; }
        public Nullable<System.DateTime> datumPodizanja { get; set; }
        public Nullable<int> serijskiBroj { get; set; }
        public string OIB { get; set; }
    
        public virtual hzzoKlijent hzzoKlijent { get; set; }
        public virtual hzzoLijekovi hzzoLijekovi { get; set; }
    }
}
