//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appoteka_v2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class hzzoLijekovi
    {
        public hzzoLijekovi()
        {
            this.hzzoRecept = new HashSet<hzzoRecept>();
        }
    
        public int serijskiBroj { get; set; }
        public string naziv { get; set; }
        public string proizvodac { get; set; }
        public Nullable<System.DateTime> rokTrajanja { get; set; }
        public Nullable<double> cijenaKupovna { get; set; }
        public Nullable<double> cijenaProdajna { get; set; }
    
        public virtual ICollection<hzzoRecept> hzzoRecept { get; set; }
    }
}
