//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appoteka_v2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class kategorijeLijekova
    {
        public kategorijeLijekova()
        {
            this.ladice = new HashSet<ladice>();
            this.lijekovi = new HashSet<lijekovi>();
        }
    
        public int IdKategorije { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
    
        public virtual ICollection<ladice> ladice { get; set; }
        public virtual ICollection<lijekovi> lijekovi { get; set; }
    }
}
