//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appoteka_v2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class ladice
    {
        public ladice()
        {
            this.kategorijeLijekova = new HashSet<kategorijeLijekova>();
        }
    
        public int IdLadice { get; set; }
        public Nullable<int> kapacitet { get; set; }
    
        public virtual ICollection<kategorijeLijekova> kategorijeLijekova { get; set; }
    }
}
