//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appoteka_v2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class lijekovi
    {
        public lijekovi()
        {
            this.kategorijeLijekova = new HashSet<kategorijeLijekova>();
            this.narudzbe = new HashSet<narudzbe>();
            this.racun = new HashSet<racun>();
        }
    
        public int serijskiBroj { get; set; }
        public string naziv { get; set; }
        public string proizvodac { get; set; }
        public System.DateTime rokTrajanja { get; set; }
        public double cijenaKupovna { get; set; }
        public double cijenaProdajna { get; set; }
        public int kolicina { get; set; }
        public int dopunsko { get; set; }
    
        public virtual ICollection<kategorijeLijekova> kategorijeLijekova { get; set; }
        public virtual ICollection<narudzbe> narudzbe { get; set; }
        public virtual ICollection<racun> racun { get; set; }
    }
}
