//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appoteka_v2._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class appotekaDBEntities : DbContext
    {
        public appotekaDBEntities()
            : base("name=appotekaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dobavljaci> dobavljaci { get; set; }
        public DbSet<kategorijeLijekova> kategorijeLijekova { get; set; }
        public DbSet<ladice> ladice { get; set; }
        public DbSet<lijekovi> lijekovi { get; set; }
        public DbSet<narudzbe> narudzbe { get; set; }
        public DbSet<racun> racun { get; set; }
        public DbSet<zaposlenici> zaposlenici { get; set; }
    }
}
