//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appoteka_v2._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HzzoDBEntities : DbContext
    {
        public HzzoDBEntities()
            : base("name=HzzoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<hzzoKlijent> hzzoKlijent { get; set; }
        public DbSet<hzzoLijekovi> hzzoLijekovi { get; set; }
        public DbSet<hzzoRecept> hzzoRecept { get; set; }
    }
}
